# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AnchorModel', '0003_anchor_userid'),
        ('RoomModel', '0004_auto_20170114_1214'),
        ('CategoryModel', '0001_initial'),
        ('UserModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchorId', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='AnchorModel.Anchor')),
                ('categoryId', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='CategoryModel.CategoryModel')),
                ('roomId', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='RoomModel.RoomModel')),
                ('userId', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='UserModel.UserModel')),
            ],
        ),
    ]
