# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 12:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CategoryModel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AnchorModel', '0001_initial'),
        ('RoomModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchorId', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='AnchorModel.Anchor')),
                ('categoryId', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='CategoryModel.CategoryModel')),
                ('roomId', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='RoomModel.RoomModel')),
                ('userId', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
