# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CategoryModel', '0001_initial'),
        ('AnchorModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('last', models.DateTimeField(auto_now_add=True)),
                ('houseCount', models.IntegerField(default=0)),
                ('followCount', models.IntegerField(default=0)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CategoryModel.CategoryModel')),
                ('ownerId', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='AnchorModel.Anchor')),
            ],
        ),
    ]
