# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomModel', '0002_auto_20170112_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='categoryId',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='houseCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='ownerId',
            field=models.IntegerField(default=-1),
        ),
    ]
