# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomModel', '0002_remove_roommodel_followcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommodel',
            name='houseCount',
        ),
    ]
