# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomModel', '0003_remove_roommodel_housecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
