# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomModel', '0003_auto_20170112_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='followCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CategoryModel.CategoryModel'),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='ownerId',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='AnchorModel.Anchor'),
        ),
    ]
