# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('signUpDate', models.DateField()),
            ],
        ),
    ]
