# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchor',
            name='signUpDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
