# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnchorModel', '0002_auto_20170205_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anchor',
            old_name='foreignUserId',
            new_name='userId',
        ),
    ]
