# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0001_initial'),
        ('AnchorModel', '0002_auto_20170112_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchor',
            name='userId',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='UserModel.UserModel'),
        ),
    ]
